#!/usr/bin/env bash
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common.sh"

init_stage "70" "activate_env"
trap 'handle_unexpected_error $? ${LINENO} "${BASH_COMMAND}"' ERR

if stage_should_skip; then
    exit 0
fi

stage_begin_work

need_stage_success() {
    local stage_id="$1"
    local description="$2"
    local state_file="${STATE_DIR}/${stage_id}.state"
    if [[ ! -f "${state_file}" ]]; then
        stage_mark_failure "${description} has not been run yet. Missing state file: ${state_file}"
    fi
    if ! grep -Fxq "status=success" "${state_file}"; then
        local status
        status="$(sed -n 's/^status=//p' "${state_file}" | head -n1)"
        stage_mark_failure "${description} is not in success state (current: ${status:-unknown}). Resolve that stage first."
    fi
}

resolve_library_dir() {
    local prefix="$1"
    local library_name="$2"
    local library_path
    library_path="$(find "${prefix}" -maxdepth 3 -name "${library_name}" | sort | head -n1)"
    if [[ -z "${library_path}" ]]; then
        stage_mark_failure "Could not find ${library_name} under ${prefix}"
    fi
    dirname "${library_path}"
}

need_stage_success "50" "Stage 50 (INET build)"
need_stage_success "60" "Stage 60 (estnet clone)"

if [[ ! -f "${OMNETPP_DIR}/setenv" ]]; then
    stage_mark_failure "OMNeT++ setenv is missing at ${OMNETPP_DIR}/setenv"
fi
if [[ ! -f "${INET_DIR}/setenv" ]]; then
    stage_mark_failure "INET setenv is missing at ${INET_DIR}/setenv"
fi

OSG_LIBDIR="$(resolve_library_dir "${OPENSCENEGRAPH_PREFIX}" "libosg.so")"
OSGEARTH_LIBDIR="$(resolve_library_dir "${OSGEARTH_27A_PREFIX}" "libosgEarth.so")"
OSG_LIBDIR_SUFFIX="${OSG_LIBDIR#${OPENSCENEGRAPH_PREFIX}}"
OSGEARTH_LIBDIR_SUFFIX="${OSGEARTH_LIBDIR#${OSGEARTH_27A_PREFIX}}"
OSGEARTH_DATA_DIR="${OSGEARTH_27A_PREFIX}/data"
PYTHON_SHIM_DIR="${THIRD_PARTY_INSTALL_DIR}/toolchain-shims/bin"
ACTIVATE_ENV_FILE="${PROJECT_ROOT}/activate_env.sh"

append_summary "activation_script=${ACTIVATE_ENV_FILE}"
append_summary "osg_libdir=${OSG_LIBDIR}"
append_summary "osgearth_libdir=${OSGEARTH_LIBDIR}"
append_summary "osg_libdir_suffix=${OSG_LIBDIR_SUFFIX}"
append_summary "osgearth_libdir_suffix=${OSGEARTH_LIBDIR_SUFFIX}"
append_summary "osgearth_data_dir=${OSGEARTH_DATA_DIR}"
append_summary "python_shim_dir=${PYTHON_SHIM_DIR}"
append_summary "activation_goal=source OMNeT++ setenv, source INET setenv, preserve OSG/osgEarth prefixes"

set_checkpoint "generate" "writing unified activation script"
cat > "${ACTIVATE_ENV_FILE}" <<EOF
#!/usr/bin/env bash
# Generated by scripts/70_activate_env.sh on $(timestamp)

if [[ "\${BASH_SOURCE[0]}" == "\$0" ]]; then
    echo "Error: source this script instead of executing it: source ./activate_env.sh" >&2
    exit 1
fi

_activate_env_root="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
_activate_env_prev_pwd="\$PWD"

if [[ ! -f "\${_activate_env_root}/versions.env" || ! -f "\${_activate_env_root}/paths.env" ]]; then
    echo "Error: project env files are missing under \${_activate_env_root}" >&2
    return 1 2>/dev/null || exit 1
fi

export PROJECT_ROOT="\${_activate_env_root}"
export WORKSPACE_ROOT="\${PROJECT_ROOT}"

. "\${PROJECT_ROOT}/versions.env"
if [[ -f "\${PROJECT_ROOT}/.env.local" ]]; then
    . "\${PROJECT_ROOT}/.env.local"
fi
. "\${PROJECT_ROOT}/paths.env"

export OMNETPP_ROOT="\${OMNETPP_DIR}"
export INET_ROOT_DIR="\${INET_DIR}"
export ESTNET_ROOT="\${ESTNET_DIR}"
export ESTNET_TEMPLATE_ROOT="\${ESTNET_TEMPLATE_DIR}"
export OPENSCENEGRAPH_PREFIX="\${OPENSCENEGRAPH_PREFIX}"
export OSGEARTH_PREFIX="\${OSGEARTH_27A_PREFIX}"

if [[ -d "\${THIRD_PARTY_INSTALL_DIR}/toolchain-shims/bin" ]]; then
    export PATH="\${THIRD_PARTY_INSTALL_DIR}/toolchain-shims/bin:\$PATH"
fi

export LD_LIBRARY_PATH="\${OSGEARTH_PREFIX}${OSGEARTH_LIBDIR_SUFFIX}:\${OPENSCENEGRAPH_PREFIX}${OSG_LIBDIR_SUFFIX}\${LD_LIBRARY_PATH:+:\${LD_LIBRARY_PATH}}"
if [[ -d "\${OSGEARTH_PREFIX}/data" ]]; then
    export OSG_FILE_PATH="\${OSGEARTH_PREFIX}/data\${OSG_FILE_PATH:+:\${OSG_FILE_PATH}}"
fi

cd "\${OMNETPP_DIR}"
. ./setenv -f >/dev/null
cd "\${INET_DIR}"
. ./setenv -f >/dev/null
cd "\$_activate_env_prev_pwd"

unset _activate_env_root
unset _activate_env_prev_pwd
EOF

chmod +x "${ACTIVATE_ENV_FILE}"

set_checkpoint "validate" "verifying unified activation script"
if ! bash -lc 'source "'"${ACTIVATE_ENV_FILE}"'" && test "${OMNETPP_ROOT}" = "'"${OMNETPP_DIR}"'" && test "${INET_ROOT}" = "'"${INET_DIR}"'" && command -v omnetpp >/dev/null && command -v inet >/dev/null && test -r "'"${OSGEARTH_DATA_DIR}"'/moon_1024x512.jpg" && case ":${OSG_FILE_PATH:-}:" in *:"'"${OSGEARTH_DATA_DIR}"'":*) true ;; *) false ;; esac'; then
    stage_mark_failure "Generated activation script failed validation. Inspect ${ACTIVATE_ENV_FILE}."
fi

stage_mark_success "Unified activation script generated and validated at ${ACTIVATE_ENV_FILE}."
